### PR TITLE
Update PR template

### PR DESCRIPTION
**Pull request by AsliRoy**
PR template has been updated and changes made accordingly to readme.

### CODE REVIEW

**Comment by AsliRoy** [comment]
@AB1908 , review please.

**Review by AB1908 — APPROVED** [review]
Looks good.

**Comment by AB1908** [comment]
I hope you don't mind me changing the commit message. Commit messages typically are in the imperative voice. Try keeping this in mind.

**Comment by AsliRoy** [comment]
Thanks for the tip! Will keep it in mind.

**Pull request merged**
